---
services:
  jwt-init:
    container_name: jwt-init
    image: alpine:3.22.0
    volumes:
      - jwttoken:/jwt
    healthcheck:
      test: ["CMD", "test", "-f", "/jwt/jwt.hex"]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      /bin/sh -c "mkdir -p /jwt &&
      if [ ! -f /jwt/jwt.hex ]; then
        apk add --no-cache openssl &&
        openssl rand -hex 32 | tr -d '\n' > /jwt/jwt.hex;
      fi"

  reth:
    container_name: reth
    image: ghcr.io/rollkit/lumen:latest
    depends_on:
      jwt-init:
        condition: service_completed_successfully
    env_file: .env
    network_mode: host
    restart: always
    volumes:
      - ./genesis.json:/root/genesis.json:ro
      - jwttoken:/root/jwt:ro
      - reth-data:/root/reth
    entrypoint: /bin/sh -c
    command:
      - |
          lumen node \
          --engine.persistence-threshold 0 \
          --engine.memory-block-buffer-target 0 \
          --chain /root/genesis.json \
          --metrics 0.0.0.0:9001 \
          --log.file.directory /root/logs \
          --authrpc.addr 0.0.0.0 \
          --authrpc.port 8551 \
          --authrpc.jwtsecret /root/jwt/jwt.hex \
          --http --http.addr 0.0.0.0 --http.port 8545 \
          --http.api "eth,net,web3,txpool" \
          --disable-discovery \
          --txpool.pending-max-count 200000 \
          --txpool.pending-max-size 200 \
          --txpool.queued-max-count 200000 \
          --txpool.queued-max-size 200 \
          --txpool.max-account-slots 2048 \
          --txpool.max-new-txns 2048 \
          --txpool.additional-validation-tasks 16 \
          --datadir /root/reth

  rollkit-evm-single-sequencer:
    container_name: sequencer
    image: ghcr.io/rollkit/rollkit-evm-single:main
    env_file: .env
    restart: always
    depends_on:
      reth-sequencer:
        condition: service_started
    volumes:
      - sequencer-data:/root/.evm-single
      - jwttoken:/root/jwt:ro
    environment:
      - EVM_ENGINE_URL=http://localhost:8551
      - EVM_ETH_URL=http://localhost:8545
      - EVM_JWT_PATH=/root/jwt/jwt.hex
      - EVM_GENESIS_HASH=0xe720f8ec96a43a741b1ab34819acfeb029ce4f083fe73c5a08c1f6a7b17a8568
      - EVM_BLOCK_TIME=500ms
      - EVM_SIGNER_PASSPHRASE=${EVM_SIGNER_PASSPHRASE}
      - PROMETHEUS_ENABLED=true
      - ROLLKIT_HOME=/root/.evm-single
    command: start
    network_mode: host

volumes:
  jwttoken:
    driver: local
  reth-data:
    driver: local
  sequencer-data:
    driver: local
  celestia-node-export:
    external: true